[package]
name = "grust"
version = "0.1.0"
edition = "2024"

[dependencies]
league-toolkit = { git = "https://github.com/LeagueToolkit/league-toolkit.git", version = "0.1.0" }

xxhash-rust = { version = "0.8.15", features = ["xxh64"] }
